name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Adjust this if you want to deploy from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Ensure this matches the Node.js version your project requires

    - name: Install dependencies
      run: npm install

    - name: Build the Angular project
      run: npm run build

    - name: Deploy Angular frontend to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL }}
      run: npx vercel --prod --token=$VERCEL

    - name: Build and Deploy API server to Vercel
      run: |
        cd backend
        npm install
        npm run build
        npx vercel --prod --token=$VERCEL_TOKEN
